(format t "~a~%" "                           *")
(format t "~a~%" "        *                                             *")
(format t "~a~%" "               *                                               *")
(format t "~a~%" "                   *                                               *")
(format t "~a~%" "                        *                                               *")
(format t "~a~%" "                                                          *      ")
(format t "~a~%" "                              *                                               *")
(format t "~a~%" "                                      *                                               *")
(format t "~a~%" "                                                  *                                               *")
(format t "~a~%" "                                                        *                                               *")
(format t "~a~%" "                                                              *                                               *")
(format t "~a~%" "                                                                      *                                               *")
(format t "~a~%" "                                                                               *                                               *")
(format t "~a~%" "                                                                                         *                                               *")
(format t "~a~%" "                                                                                                 *                                               *")
(format t "~a~%" "                                                                                                          *      ")
(format t "~a~%" "                                                                                                                          *")
